### ISSUE TITLE
would you consider adding a few carriers?

### ISSUE THREAD

**Issue by zombiehoffa** [jat255/PackageMate#1]
if this had purolator, dynamex, intelcom, canada post, pitney bowes, and speedpak (https://www.orangeconnex.com/tracking?language=en&trackingnumber=)

it would be perfect for me.

**Comment by jat255** [comment]
While I don't have the time to add these carriers, I would be happy to review a pull request if you'd like to submit one, you can follow the instructions [here](https://github.com/jat255/PackageMate#how-to-contribute) to add support for them. It's definitely easier if the carrier has an API available, as the web scraping process is not very robust.
