### ISSUE TITLE
Invalid host head when behind NGiNX reverse proxy

### ISSUE THREAD

**Issue by 12nick12** [jat255/PackageMate#9]

**Comment by jat255** [comment]
@12nick12 I'm not sure what you mean by this, or how to fix it, since I don't use an nginx reverse proxy. If there's something I can change to fix it, please let me know, otherwise I'm going to close this in a couple of days.

**Comment by jat255** [comment]
I'm going to close this. I've been successfully been using PackageMate behind a reverse proxy using Caddy with the following configuration:

```
packagemate.example.com {
        reverse_proxy 192.168.1.1 {
                header_up Host {http.reverse_proxy.upstream.hostport}
        }
}
```

Please re-open if this is still an issue for you.

**Comment by mph88** [comment]
For anyone struggling to get this to work in nginx proxy manager you need to add `proxy_set_header Host 127.0.0.1;` under a custom location of /.
